// export let products = [
//   {
//     id: 1,
//     name: "samsung note3",
//     price: 20000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "hello samsung",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 2,
//     name: "redmi note5 pro",
//     price: 20000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "hello redmi",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 3,
//     name: "redmi note5",
//     price: 15000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 4,
//     name: "apple",
//     price: 25000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 5,
//     name: "samsung note3",
//     price: 20000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "hello samsung",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 6,
//     name: "redmi note5 pro",
//     price: 20000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "hello redmi",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 7,
//     name: "redmi note5",
//     price: 15000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
//   {
//     id: 8,
//     name: "apple",
//     price: 25000,
//     image: "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
//     countInstock: 10,
//     description: "",
//     reviews: [],
//     rating: 4,
//     category: "electronics",
//   },
// ];
